#!/bin/sh
#
# mbp-parse-status - parses status output from mbp-gather for analysis
#
# Copyright (C) 2014 by Chris Pappalardo (cpappala@yahoo.com)
#
# Some elements originally published in High Performance MySQL (3rd edition), Schwartz
# Copyright (C) 2012 Baron Schwartz, et al

# supply filenames on the command-line
awk '
   BEGIN {
      printf "#ts date time load QPS queries threads_connected threads_running";
      fmt = " %.2f";
   }
   /^TS/ { # The timestamp lines begin with TS.
      ts      = substr($2, 1, index($2, ".") - 1);
      load    = NF - 2;
      diff    = ts - prev_ts;
      prev_ts = ts;
      printf "\n%s %s %s %s", ts, $3, $4, substr($load, 1, length($load)-1);
   }
   /Queries/ {
      printf fmt, ($2-Queries)/diff;
      Queries=$2
   }
   /Threads_connected/{tc=$2}
   /Threads_running/{printf " %5d %5d %5d", Queries, tc, $2}
   END { printf "\n" }
   ' "$@"
